Union types
php-strictus/strictus pull request #20
Opened 2023-06-13 03:28 UTC by hungthai1401

Hi @WendellAdriel ,
This PR introduces union types. I use flow chart to explain my implementation.

```mermaid
flowchart TD
    A[StrictusUnion] --> B{Validate Types}
    B -->|Yes| C{Validate Value}
    B -->|No| Z[StrictusTypeException]
    C -->|Yes| D{Detect Value Type}
    C -->|No| Z[StrictusTypeException]
    D -->|Yes| E[Set Value]
    D -->|No| Z[StrictusTypeException]
    A[StrictusUnion] --> F[Update Value] --> G{Immutable}
    G -->|Yes| Y[ImmutableStrictusException]
    G -->|No| C
```

Greetings and thanks,
Thai

2023-06-13 09:15 UTC, WendellAdriel requested changes
Besides the changes requested, you need to add the needed docs for the Union types

2023-06-13 09:15 UTC, WendellAdriel commented on src/Exceptions/StrictusTypeException.php
> +        return new self(sprintf('Not support %s type', $type));
Use double quotes with variable wrapped in {} instead of sprintf

2023-06-13 09:15 UTC, WendellAdriel commented on src/Interfaces/StrictusTypeInterface.php
> + * @property mixed $value
Why this is needed?

2023-06-13 09:15 UTC, WendellAdriel commented on src/Strictus.php
> +    public static function nullableUnion(array $types, mixed $value, bool $nullable = false): StrictusUnion
Remove nullable parameter here

2023-06-13 09:15 UTC, WendellAdriel commented on src/Types/StrictusUnion.php
> +        if ($value instanceof UnitEnum) {
What happens with BackedEnum?

2023-06-13 09:15 UTC, WendellAdriel commented on src/Types/StrictusUnion.php
> +    private function getStritusType(mixed $value): ?StrictusTypeInterface
Rename to getStrictusType

2023-06-13 09:15 UTC, WendellAdriel commented on src/Types/StrictusUnion.php
> +    private function getInstanceableStritusType(mixed $value): StrictusTypeInterface
Rename to getInstanceableStrictusType

2023-06-13 09:15 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +    $nullValue = Strictus::nullableUnion([Type::ENUM, Type::INSTANCE], null);
Test trying to assign a different Enum other than MyEnum because it shouldn't allow this.

2023-06-13 09:17 UTC, hungthai1401 commented on src/Types/StrictusUnion.php
> +    private function getStritusType(mixed $value): ?StrictusTypeInterface
Could you suggest for me one name?

2023-06-13 09:47 UTC, hungthai1401 commented
@WendellAdriel I got it. I have fixed your comments

2023-06-13 10:54 UTC, WendellAdriel requested changes

2023-06-13 10:54 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +    $newValue = Strictus::union([Type::OBJECT, Type::INSTANCE], new MyDummyClass());
This is not resolved.
The idea is to instantiate a variable with ClassA per example
And then trying to update the value with ClassB and it should fail

2023-06-13 10:59 UTC, hungthai1401 commented on tests/Unit/UnionTest.php
> +    $nullValue = Strictus::nullableUnion([Type::ENUM, Type::INSTANCE], null);
@WendellAdriel do you have any ideas to solve it?

2023-06-14 09:06 UTC, WendellAdriel requested changes

2023-06-14 09:06 UTC, WendellAdriel commented on src/Types/StrictusUnion.php
> +    /** @var array<string, string>|null */
This should be array<string, class-string>|null

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toBe(true)
Use toBeTrue instead

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toBe(true);
Use toBeTrue instead

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +    $newValue = Strictus::union([Type::OBJECT, Type::INSTANCE], new MyDummyClass());
This is still not doing what was asked.
Please check my first comment again

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toEqual((object) ['foo' => 'bar']);
Use toBe instead

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toEqual((object) ['foo' => 'bar'])
Use toBe instead

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toEqual((object) ['foo' => 'bar']);
Use toBe instead

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toEqual((object) ['bar' => 'foo']);
Use toBe instead

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toEqual(null)
Use toBe instead

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toEqual(null);
Use toBe instead

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toEqual(MyDummyBackedEnum::BAR)
Use toBe instead

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toEqual('foo')
Use toBe instead

2023-06-14 09:06 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toEqual('foo')
Use toBe instead

2023-06-14 09:50 UTC, hungthai1401 commented on tests/Unit/UnionTest.php
> +        ->toEqual((object) ['foo' => 'bar']);
I think we have to use `toEqual` instead of `toBe` because of the difference reference

2023-06-14 09:56 UTC, hungthai1401 commented on src/Types/StrictusUnion.php
> +    /** @var array<string, string>|null */
it can't pass PHPStan with class-string

2023-06-14 10:04 UTC, WendellAdriel commented on tests/Unit/UnionTest.php
> +        ->toEqual((object) ['foo' => 'bar']);
Is it failing with toBe?

2023-06-14 10:06 UTC, WendellAdriel commented on src/Types/StrictusUnion.php
> +    /** @var array<string, string>|null */
You probably need more changes in the code because this is not a general string, the instance is a class-string of the class you instantiate

2023-06-14 10:06 UTC, WendellAdriel commented on src/Types/StrictusUnion.php
> +    private ?array $instance = null;
Since this is an array, rename to instances

2023-06-14 10:08 UTC, hungthai1401 commented on tests/Unit/UnionTest.php
> +        ->toEqual((object) ['foo' => 'bar']);
yes, it's failed

2023-06-14 10:20 UTC, hungthai1401 commented on tests/Unit/UnionTest.php
> +        ->toEqual((object) ['foo' => 'bar']);
https://github.com/php-strictus/strictus/blob/main/tests/Unit/ObjectTest.php#L47 same with your usage

2023-06-15 08:58 UTC, WendellAdriel requested changes

2023-06-15 08:58 UTC, WendellAdriel commented on phpstan.neon
> +    ignoreErrors:
Why are you adding this?
This shouldn't be needed, you should check the code to update where needed instead of ignoring the error

2023-06-15 09:28 UTC, hungthai1401 commented on phpstan.neon
> +    ignoreErrors:
I have an error with PHPStan. We want class-string but, PHPStan want string. How I can solve?

2023-06-15 09:55 UTC, WendellAdriel commented on phpstan.neon
> +    ignoreErrors:
You need to check the code to change the places where the instances property is used to add the property in the PHPDOC as class-string. Taking a quick look the first place is in the setInstance method. After that check if any other changes are needed.

2023-06-15 10:55 UTC, hungthai1401 commented
@WendellAdriel I have fixed them

2023-06-23 09:18 UTC, WendellAdriel requested changes

2023-06-23 09:18 UTC, WendellAdriel commented on src/Types/StrictusUnion.php
> +        /** @var class-string $instance */
This should be typing the method parameter in the PHPDOC block instead

2023-06-23 10:39 UTC, hungthai1401 commented on src/Types/StrictusUnion.php
> +        /** @var class-string $instance */
@WendellAdriel done

2023-06-23 13:16 UTC, WendellAdriel approved these changes
Thanks for the help with this, @hungthai1401!!!

2023-06-23 13:16 UTC, merged

2023-06-23 14:18 UTC, hungthai1401 commented
@WendellAdriel hope we can develop more features!!!